local todoage = require("todoage")

describe("setup keyword validation", function()
	it("accepts valid alphanumeric keywords", function()
		assert.has_no.errors(function()
			todoage.setup({ keywords = { "TODO", "FIXME" } })
		end)
	end)

	it("accepts keywords with underscores", function()
		assert.has_no.errors(function()
			todoage.setup({ keywords = { "TODO_FIXME" } })
		end)
	end)

	it("accepts lowercase keywords", function()
		assert.has_no.errors(function()
			todoage.setup({ keywords = { "todo" } })
		end)
	end)

	it("accepts keywords with digits", function()
		assert.has_no.errors(function()
			todoage.setup({ keywords = { "TODO2" } })
		end)
	end)

	it("rejects keywords with leading non-word characters", function()
		assert.has_error(function()
			todoage.setup({ keywords = { "@TODO" } })
		end)
	end)

	it("rejects keywords with trailing non-word characters", function()
		assert.has_error(function()
			todoage.setup({ keywords = { "TODO:" } })
		end)
	end)

	it("rejects keywords containing pattern metacharacters", function()
		assert.has_error(function()
			todoage.setup({ keywords = { "TODO.+" } })
		end)
	end)

	it("rejects empty string keywords", function()
		assert.has_error(function()
			todoage.setup({ keywords = { "" } })
		end)
	end)

	it("rejects non-string keywords", function()
		assert.has_error(function()
			todoage.setup({ keywords = { 42 } })
		end)
	end)

	it("rejects when any keyword in a mixed list is invalid", function()
		assert.has_error(function()
			todoage.setup({ keywords = { "TODO", "FIXME:" } })
		end)
	end)
end)
